{% set name = "explainerdashboard" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/explainerdashboard-{{ version }}.tar.gz
  sha256: 2ddb44ce3d767cdd8392d55676232f7c8cf8f242e5c67e761e99fe221846ea44

build:
  number: 0
  noarch: python
  entry_points:
    - explainerdashboard = explainerdashboard.cli:explainerdashboard_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - click
    - orjson
    - dash
    - dash-auth
    - dash-bootstrap-components ==0.8.3
    - dash-html-components ==2.0.0
    - dash-core-components ==2.0.0
    - dash-table ==5.0.0
    - dtreeviz >=1.0
    - flask_simplelogin
    - joblib
    - jupyter-dash
    - numpy
    - oyaml
    - pandas
    - scikit-learn
    - shap >=0.37
    - waitress

test:
  imports:
    - explainerdashboard
    - explainerdashboard.dashboard_components
  commands:
    - pip check
    - explainerdashboard --help
  requires:
    - pip

about:
  home: https://github.com/oegedijk/explainerdashboard
  summary: explainerdashboard allows you quickly build an interactive dashboard to explain the inner workings of your machine learning model.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
    - oegedijk
