{% set name = "explainerdashboard" %}
{% set version = "0.4.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/explainerdashboard-{{ version }}.tar.gz
  sha256: 93b3ef54f09bd02969a07afe94ef5b1305a71e699ed5894b7fb250d6171a73ac

build:
  number: 1
  noarch: python
  entry_points:
    - explainerdashboard = explainerdashboard.cli:explainerdashboard_cli
    - explainerhub = explainerdashboard.cli:explainerhub_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - python >=3.8
    - click
    - dash >=2.10,<3
    - dash-auth
    - dash-bootstrap-components >=1,<3
    - dtreeviz >=2.1
    - flask-wtf >=1.1
    - graphviz >=0.18.2
    - flask_simplelogin
    - joblib
    - jupyter-dash >=0.4.1
    - numpy <2
    - oyaml
    - pandas >=1.1
    - plotly <6
    - scikit-learn >=1.1
    - shap >=0.42.1
    - waitress

test:
  imports:
    - explainerdashboard
    - explainerdashboard.dashboard_components
  commands:
    - pip check
    - explainerdashboard --help
    - explainerhub --help
  requires:
    - pip

about:
  home: https://github.com/oegedijk/explainerdashboard
  summary: explainerdashboard allows you quickly build an interactive dashboard to explain the inner workings of your machine learning model.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
    - oegedijk