{% set name = "explainerdashboard" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/explainerdashboard-{{ version }}.tar.gz
  sha256: d66a2dea454d11961329d833e4fbaba3b35ff7c75d1744efbcffb102371fd39b

build:
  number: 0
  noarch: python
  entry_points:
    - explainerdashboard = explainerdashboard.cli:explainerdashboard_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click
    - dash
    - dash-auth
    - dash-bootstrap-components
    - dtreeviz >=1.0
    - flask_simplelogin
    - joblib
    - jupyter-dash
    - numpy
    - oyaml
    - pandas
    - pdpbox
    - python
    - scikit-learn
    - shap >=0.37
    - shortuuid
    - slicer ==0.0.3
    - waitress

test:
  imports:
    - explainerdashboard
    - explainerdashboard.dashboard_components
  commands:
    - pip check
    - explainerdashboard --help
  requires:
    - pip

about:
  home: https://github.com/oegedijk/explainerdashboard
  summary: explainerdashboard allows you quickly build an interactive dashboard to explain the inner workings of your machine learning model.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
    - oegedijk
